---
repos:

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-json
          - id: check-yaml
          - id: pretty-format-json
            args:
            - --autofix
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/psf/black
      rev: 22.12.0
      hooks:
          - id: black

    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            args: [--profile, black, --filter-files]

    - repo: https://github.com/asottile/setup-cfg-fmt
      rev: v2.2.0
      hooks:
          - id: setup-cfg-fmt
